# Generated by Django 5.2.14 on 2026-08-08 20:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('ruc_dni', models.CharField(blank=True, max_length=11, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_correlativo', models.CharField(max_length=20, unique=True)),
                ('solicitante_nombre', models.CharField(max_length=150)),
                ('solicitante_telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_entrega_acordada', models.DateField()),
                ('estado_actual', models.CharField(choices=[('Registrado', 'Registrado'), ('Espera material', 'Espera material'), ('En producción', 'En producción'), ('En el taller', 'En el taller'), ('En la tienda', 'En la tienda'), ('Entregado', 'Entregado')], default='Registrado', max_length=50)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pedidos', to='api.marca')),
            ],
            options={
                'db_table': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PagoPedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Yape/Plin', 'Yape/Plin'), ('Transferencia', 'Transferencia')], max_length=20)),
                ('tipo_pago', models.CharField(choices=[('Adelanto', 'Adelanto'), ('Pago Entrega', 'Pago Entrega'), ('Abono', 'Abono')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='api.pedido')),
            ],
            options={
                'db_table': 'pagos_pedido',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadosPedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(blank=True, choices=[('Registrado', 'Registrado'), ('Espera material', 'Espera material'), ('En producción', 'En producción'), ('En el taller', 'En el taller'), ('En la tienda', 'En la tienda'), ('Entregado', 'Entregado')], max_length=50, null=True)),
                ('estado_nuevo', models.CharField(choices=[('Registrado', 'Registrado'), ('Espera material', 'Espera material'), ('En producción', 'En producción'), ('En el taller', 'En el taller'), ('En la tienda', 'En la tienda'), ('Entregado', 'Entregado')], max_length=50)),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ejecutado_por', models.CharField(default='Sistema', max_length=100)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='api.pedido')),
            ],
            options={
                'db_table': 'historial_estados_pedido',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('precio_millar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_ciento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_unidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='productos', to='api.categoria')),
            ],
            options={
                'db_table': 'tipos_producto',
                'ordering': ['nombre'],
                'unique_together': {('categoria', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('unidad_medida', models.CharField(choices=[('Unidad', 'Unidad'), ('Ciento', 'Ciento'), ('Millar', 'Millar')], default='Millar', max_length=20)),
                ('precio_base_calculado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_final_acordado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url_vectorial', models.CharField(blank=True, max_length=512, null=True)),
                ('url_fotografia', models.CharField(blank=True, max_length=512, null=True)),
                ('tamano_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('color_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('num_colores_estampado', models.IntegerField(blank=True, null=True)),
                ('tipo_servicio', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.pedido')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.tipoproducto')),
            ],
            options={
                'db_table': 'detalles_pedido',
            },
        ),
        migrations.CreateModel(
            name='ColorProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colores', to='api.categoria')),
            ],
            options={
                'db_table': 'colores_producto',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('categoria', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Tamano',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('unidad_medida', models.CharField(default='pulgadas', max_length=20)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanos', to='api.categoria')),
            ],
            options={
                'db_table': 'tamanos',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('categoria', 'nombre', 'unidad_medida')},
            },
        ),
    ]
