# Generated by Django 5.2.14 on 2026-08-10 05:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProductoColor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_rel', to='api.colorproducto')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colores_rel', to='api.tipoproducto')),
            ],
            options={
                'db_table': 'tipo_producto_colores',
                'ordering': ['orden'],
                'unique_together': {('tipo_producto', 'color')},
            },
        ),
        migrations.CreateModel(
            name='TipoProductoTamano',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tamano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_rel', to='api.tamano')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tamanos_rel', to='api.tipoproducto')),
            ],
            options={
                'db_table': 'tipo_producto_tamanos',
                'ordering': ['orden'],
                'unique_together': {('tipo_producto', 'tamano')},
            },
        ),
    ]
