# Generated by Django 5.2.14 on 2026-08-11 08:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tipoproductocolor_tipoproductotamano'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('VENDEDOR', 'Vendedor'), ('OPERARIO', 'Operario')], default='VENDEDOR', max_length=20)),
                ('nombre_completo', models.CharField(blank=True, default='', max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfiles_usuario',
                'ordering': ['user__username'],
            },
        ),
    ]
