# Generated by Django 5.2.14 on 2026-08-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='solicitante_nombre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
